### ISSUE TITLE
【UI组件】File inputs - 示例，基本用法的示例功能不全 

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#101]
UI组件 - File inputs - 示例；基本用法的示例功能不全；
![文件上传 - 基本用法示例功能不全](https://user-images.githubusercontent.com/95004531/146476631-cd8433aa-1074-4d4e-9406-d3838c9c1631.png)

**Comment by capdiem** [comment]
Supported.
