### ISSUE TITLE
MSlider 滑动块应支持数值类型，而不是固定double

### ISSUE THREAD

**Issue by kimdiego2098** [BlazorComponent/MASA.Blazor#1021]
**Describe the bug**

MSlider 滑动块应支持数值类型，而不是固定double，下面是使用TValue为int时报错

![F H{}RRN1E3_FZ }(H`5M](https://user-images.githubusercontent.com/82756760/219604205-d4c6a1d8-ce42-497a-b4a5-f5dd243adc22.png)

![~`D1W@{RCDNV}L%BAJDJI%Q](https://user-images.githubusercontent.com/82756760/219604246-a6aa5120-9383-44e3-88bf-07e0066a5ce2.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by capdiem** [comment]
Thanks for contacting us, it would be fixed in `1.0.0-preview.7`.
