### ISSUE TITLE
Change the UI of Toast to something like a Snackbar

### ISSUE THREAD

**Issue by capdiem** [BlazorComponent/MASA.Blazor#1034]
- At present, the UI of Toast is not in line with Material Design, so it is suitable to use Snackbar directly.
- IPopupService
  - `IPopupService.AlertAsync` use the Snackbar component internally instead of the Alert component, so should change it to `IPopupService.ShowSnackbarAsync`.
  - Toasts may not be needed, if there are something like `IPopupService.EnqueueSnackbarAsync`.

@doddgu

**Comment by doddgu** [comment]
Enquiue? Snackbar, Toast is not the same. Toast may be applicable when there are many contents and each one is emphasized.

**Comment by capdiem** [comment]
@doddgu the UI(style or css) of Toasts is not in line with Material Design. Use Snackbar and let it stack, for example: https://notistack.com/features/basic
