### ISSUE TITLE
MSlider在移动设备下存在拖动滑块时组件会卡死的Bug

### ISSUE THREAD

**Issue by mookeview** [BlazorComponent/MASA.Blazor#1041]
MSlider在移动设备下，不管是实体机（iphone 13 pro max）还是浏览器中模拟的手机，一拖动滑块整个Slider组件就会卡死不响应
<img width="402" alt="bug1" src="https://user-images.githubusercontent.com/121916399/221559411-919d460f-8798-48b3-bd14-4dfbe2b0968a.png">
<img width="321" alt="bug2" src="https://user-images.githubusercontent.com/121916399/221559423-ad3bad78-80de-41c0-bdfe-5f4541dc5a48.png">
<img width="556" alt="bug3" src="https://user-images.githubusercontent.com/121916399/221559428-217e4165-4ded-45b5-8741-46eb29f8e96a.png">

**Comment by capdiem** [comment]
@mookeview 你用的哪个版本？我测试了[1.0.0-preview的文档](https://docs.masastack.com/blazor/components/sliders)没有出现这种情况

**Comment by mookeview** [comment]
我用的就是最新版。官方文档确实正常，但在我创建的两个项目中都是这样的现象，不知道是什么原因

**Comment by mookeview** [comment]
我已将测试文档发您邮箱了，有空帮我查看下，非常感谢！

**Comment by mookeview** [comment]
换系统，换IDE都尝试过了，还是出现同个问题，难道是项目配置问题，请帮忙解决下，感谢！ @capdiem

**Comment by capdiem** [comment]
@mookeview 我在新项目里也复现了，正在调查

**Comment by mookeview** [comment]
非常期待您的好消息！ @capdiem

**Comment by capdiem** [comment]
@mookeview 多谢反馈，问题已经找到，1.0.0-preview.7 会修复这个问题。

**Comment by mookeview** [comment]
谢谢，现在有应急的、昨时的解决方案吗？我现在使用的一个小项目亟待解决这个问题，再次感谢！ @capdiem

**Comment by doddgu** [comment]
非常急可以用 [0.7.0-alpha.2445](https://www.nuget.org/packages/Masa.Blazor/0.7.0-alpha.2445) 后面的alpha版本，目前正在编译中

**Comment by doddgu** [comment]
已经出来了，[0.7.0-alpha.2454](https://www.nuget.org/packages/Masa.Blazor/0.7.0-alpha.2454)，欢迎尝试

**Comment by mookeview** [comment]
己经解决，太感谢了！发自我的 iPhone在 2023年2月28日，21:12，鬼谷子 ***@***.***> 写道：﻿
已经出来了，0.7.0-alpha.2454，欢迎尝试
