### ISSUE TITLE
能做个TDesign风格的么？

### ISSUE THREAD

**Issue by shuaqq2004** [BlazorComponent/MASA.Blazor#1047]
项目挺好的，一直在关注。
15年开始使用Angular和Material 设计规范，后来弃了。
感觉Material 真心不适合中文，只适合拉丁文。现在用AntBlazor。
纵观国内的Design， 其实如果能适配腾讯的TDesign, 出TDesign Blazor就好了。

**Comment by china-live** [comment]
是的，感觉Bootstrap、Material这类UI框架空白、间距太大，简单的demo看起来漂亮，但实用性不强，整体看起来比较松散。
还有就是，一些使用习惯上也不适合中文，比如Autocompletes（自动补全）这个，英文可能用起来还不错，但中文内容就很难受了，要想好用就得单独优化，比如支持按键时转按拼音检索，甚至像百度搜索框那边还能适配五笔，但这个难度较大，成本也相对较高，大多数时候没省略了。

**Comment by doddgu** [comment]
> 是的，感觉Bootstrap、Material这类UI框架空白、间距太大，简单的demo看起来漂亮，但实用性不强，整体看起来比较松散。 还有就是，一些使用习惯上也不适合中文，比如Autocompletes（自动补全）这个，英文可能用起来还不错，但中文内容就很难受了，要想好用就得单独优化，比如支持按键时按拼音检索，甚至像百度搜索框那边还能适配五笔，但这个难度较大，成本也相对较高，大多数时候就省略了。

空白较大的问题，在B站视频有个用MASA Blazor还原Ant Design Pro风格的可以看下，很简单。另外剧透一下 2.0 将会支持 Provider 可以在项目启动时统一修改 padding, margin 等默认参数。敬请期待。。。

至于中文适配问题，这个是feature，可以提issue，我们抽空会支持，或者也接受PR。
