### ISSUE TITLE
EnqueuedSnackbars has no method to change the position

### ISSUE THREAD

**Issue by Yu-Core** [BlazorComponent/MASA.Blazor#1057]
Toast has method to change the position, but EnqueuedSnackbars has no.

![image](https://user-images.githubusercontent.com/96511239/222907829-80df26cb-4b6c-47b3-9914-336322d12f8c.png)

**Comment by doddgu** [comment]
Snackbar has no position property. It's by design(Material Design).

**Comment by Yu-Core** [comment]
I see that it can be configured here
![image](https://user-images.githubusercontent.com/96511239/222944540-edc27c42-af51-4c36-af00-a3c7abace03e.png)

**Comment by doddgu** [comment]
@capdiem PTAL

**Comment by capdiem** [comment]
@Yu-Core yes, so this issue can be closed, right?
