### ISSUE TITLE
单文件发布时，运行报错

### ISSUE THREAD

**Issue by kimdiego2098** [BlazorComponent/MASA.Blazor#1074]
**Describe the bug**
![Y$VCUUEE@ V2W) 1RC NCFM](https://user-images.githubusercontent.com/82756760/224487059-e68cf9d4-1e9a-411d-b446-d9d539654d5a.png)
assemblyPath在单文件发布时会是null值
可以改成AppContext.BaseDirectory [查看微软文档说明](https://learn.microsoft.com/zh-cn/dotnet/core/deploying/single-file/overview?tabs=cli#api-incompatibility)
![image](https://user-images.githubusercontent.com/82756760/224487746-5e5a6aaf-2543-4c86-a09a-4f414610efed.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by capdiem** [comment]
@wuweilaiya please take a look
