### ISSUE TITLE
在删除MChip时阻止点击事件传递至SelectionContent

### ISSUE THREAD

**Issue by An0rangetree** [BlazorComponent/MASA.Blazor#1076]
**Is your feature request related to a problem? Please describe.**

- 场景
官方blazor-pro案例：https://blazor-pro.masastack.com/app/todo

- 位置
TodoDetail中MForm->MSelect->SelectionContent->MChip

- 问题
点击删除tag，会顺带点开SelectionContent，我认为这里的点击操作做了多余的事情

- 示意
![I)QEK_D@$QV29})5 R(AC8S](https://user-images.githubusercontent.com/87368283/224494116-eeef9a54-ab83-46c8-a1d5-2928d720e39e.png)

**Describe the solution you'd like**

- 需求
只删除tag，而不点开SelectionContent

- 方式
最好只需加一个属性，我只知道用@onclick:stopPropagation，但如示意图，没有找到符合我需求的添加位置

**Describe alternatives you've considered**

- 交流群大佬的建议
1. 把 closeclick 的冒泡暴露出来
2. 写个 micon 自定义的 close 然后阻止冒泡

**Additional context**
初学Blazor和MASA，欢迎任何简单或复杂的解决办法

**Comment by capdiem** [comment]
@An0rangetree OnCloseClick内部应该是默认阻止冒泡的，1.0.0-preview.9 修复。急的话就自定义CloseIcon：
``` cshtml
<MChip> xxx <MIcon OnClick='() => {}'  OnClickStopPropagation>mdi-close<MIcon></MChip>
```
