### ISSUE TITLE
No response to upload the modified file

### ISSUE THREAD

**Issue by binwan-dev** [BlazorComponent/MASA.Blazor#1090]
**Describe the bug**
Use MInputFile component. Upload file 'A', and modify content in the file 'A', and repeat upload file 'A'. the file 'A' which is modified content cannot be upload, it is no response.

**To Reproduce**
1. Upload file 'A'
2. Modify content in the file 'A' 
3. Upload file 'A'
4. See the file 'A' which is modified content cannot be upload. It is no response.

**Comment by capdiem** [comment]
The behavior is consistent with `<input type='file' />`, so this is not a bug. There are two ways to solve your problem.

- set the `Value` to `null` after uploading your file.
- or set the `Value` to `null` on `OnClick`, but it doesn't work for now, I plan to support this in next preview version.
