### ISSUE TITLE
NavigationDrawer设置Fixed属性时,Overlay没有对应设置Fixed属性

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#11]
如题
![企业微信截图_1639534738966](https://user-images.githubusercontent.com/95004531/146328187-38bd5ff5-395d-4fbf-856d-3adc973b52ca.png)
![企业微信截图_16395346905472](https://user-images.githubusercontent.com/95004531/146328190-8850998e-ab26-43cd-9895-8b438439ad33.png)

**Comment by wangzengxing** [comment]
@LazyEar0
