### ISSUE TITLE
【UI组件】Chips - 示例 - 其他 - 过滤，示例中点击放大镜，搜索框应变为蓝色 

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#117]
UI组件 - Chips - 示例 - 其他 - 过滤；示例中点击放大镜，搜索框应变为蓝色
![纸片 - 过滤示例中点击放大镜，搜索框应变为蓝色](https://user-images.githubusercontent.com/95004531/146479345-26fef695-b49e-4100-8884-83b6504594ce.png)

**Comment by wangzengxing** [comment]
This is a bug for text-field.

**Comment by capdiem** [comment]
maybe fixed in 1.0.0 preview, cannot reproduce at present.
