### ISSUE TITLE
【UI组件】Chips - 示例 - 其他，自定义列表和过滤的示例中，搜索框中输入内容后，下方应自动显示搜索结果 

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#118]
UI组件 - Chips - 示例 - 其他；自定义列表和过滤的示例中，搜索框中输入内容后，下方应自动显示搜索结果，现需要回车或点击页面方出现搜索结果；
![纸片 - 其他 - 自定义列表的示例中，搜索框中输入内容后，下方应自动显示搜索结果](https://user-images.githubusercontent.com/95004531/146479422-a2e79a93-720e-4bd5-93c1-72b569f32b8f.png)
![纸片 - 其他 - 过滤的示例中，搜索框中输入内容后，下方应自动显示搜索结果](https://user-images.githubusercontent.com/95004531/146479427-06def1ac-09b2-4e83-80ba-825ddb3f7ac7.png)

**Comment by wangzengxing** [comment]
This is caused by text-field component,and has been fixed,so we will close this.
