### ISSUE TITLE
【UI组件】组件“Buttons Floating Action Button（按钮 浮动动作按钮）”缺失 

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#121]
组件“Buttons Floating Action Button（按钮 浮动动作按钮）”缺失
![组件“浮动动作按钮”缺失](https://user-images.githubusercontent.com/95004531/146479689-cdcd714b-cdf8-4537-97ad-f94385b1abe8.png)

**Comment by capdiem** [comment]
Have added.
