### ISSUE TITLE
【UI组件】ToolBars - 示例 - 属性 - 基本使用的示例功能不全 

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#125]
UI组件 - ToolBars - 示例 - 属性 - 基本使用；示例的功能不全
![工具栏 - 基础用法示例功能缺失](https://user-images.githubusercontent.com/95004531/146482361-a0c5d8da-8047-4095-be4b-e707e2fba677.png)

**Comment by wangzengxing** [comment]
we will supported this feature in 0.4.0 milestone.

**Comment by capdiem** [comment]
Added.
