### ISSUE TITLE
【UI组件】AppBars - 用例模块的示例功能不全 

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#126]
UI组件 - AppBars - 用例；示例功能不全
![APP bars - 用例模块的示例功能不全](https://user-images.githubusercontent.com/95004531/146482408-8253bb29-ac54-4b47-ae99-78a158de4a45.png)

**Comment by wangzengxing** [comment]
we will supported this in 0.4.0 milestone.

**Comment by capdiem** [comment]
Added.
