### ISSUE TITLE
【UI组件】Alert - 示例“在codepen中编辑”功能缺失 

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#131]
UI组件 - Alert - 示例；“在codepen中编辑”功能缺失；
![提示框 示例属性 在“codepen中编辑”功能缺失](https://user-images.githubusercontent.com/95004531/146482898-79c2c931-7417-475d-9254-f2dd0327092f.png)

**Comment by wangzengxing** [comment]
we will not supported this feature.
