### ISSUE TITLE
【UI组件】tabs - 从右侧tab切换至左侧tab时，下方内容的动效应为从左侧向右侧滑动

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#134]
如题
![切换tab动效](https://user-images.githubusercontent.com/95004531/146481659-6cf34105-ded0-43d2-a275-bba4875b56f1.png)

**Comment by wangzengxing** [comment]
@capdiem If you close an issue,give a reason or description
