### ISSUE TITLE
[Styles and animations] Transitions - Input Enter to increase the number of Tasks

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#157]
![Input Enter to increase the number of Tasks](https://user-images.githubusercontent.com/95004531/147327445-a5d3dca4-87cb-404d-8b72-d15d46e0599b.png)

**Comment by wangzengxing** [comment]
We will fix this when transition been refactored.

**Comment by capdiem** [comment]
Fixed.
