### ISSUE TITLE
Autocompletes - The contents of the input box are incorrect when the search option is selected

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#182]
![autocomplete0](https://user-images.githubusercontent.com/95004531/147736113-1aef2e37-6992-4639-a428-6cca8acc3ce7.png)
![autocomplete1](https://user-images.githubusercontent.com/95004531/147736125-43b6d7ef-ac03-427b-be7f-edb7ddfcc7ee.png)

**Comment by capdiem** [comment]
Unable to reproduce.
