### ISSUE TITLE
Presets - Confirm , In English, the text of the confirm is not translated into English 

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#215]
![微信截图_20211231184159](https://user-images.githubusercontent.com/95004531/147819267-34336611-bc8e-491a-9d87-5f94b83e537d.png)

**Comment by doddgu** [comment]
I think, keep the sample in English.

**Comment by capdiem** [comment]
@doddgu why don't remove the PConfirm component, we already have PopupService.

**Comment by doddgu** [comment]
confirm is dialog,popupservice don't have dialog. and confirm is your pr?

**Comment by capdiem** [comment]
PopupService has confirm dialog. PConfirm is my PR.

**Comment by doddgu** [comment]
ok，popupservice hasconfirm，pconfirm can be removed
