### ISSUE TITLE
DataTable 勾选时候  同一个名字的会自动勾选   能不能只勾选需要的行？

### ISSUE THREAD

**Issue by huxinshuo** [BlazorComponent/MASA.Blazor#2282]
### Proposal and motivation

DataTable 勾选时候  同一个名字的会自动勾选   能不能只勾选需要的行？
![微信截图_20241214211938](https://github.com/user-attachments/assets/8260a071-1784-4e3d-bf3c-8a930b7ef0d3)

**Comment by capdiem** [comment]
@huxinshuo 保证ItemKey唯一。

**Comment by huxinshuo** [comment]
@capdiem 
Func<TItem, string>

能否支持int   ItemKey="r => r.ID" 提示ID无法转换为string

**Comment by capdiem** [comment]
@huxinshuo `r.ID.ToString()`

**Comment by huxinshuo** [comment]
可以了
