### ISSUE TITLE
Text fields - Full width with counter ,Error 404 is reported if the search result is empty

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#229]
![404](https://user-images.githubusercontent.com/95004531/148034719-1b0591dd-28d9-4ff2-a91f-2f0fa7fe9902.png)
![404-](https://user-images.githubusercontent.com/95004531/148034728-46d7d4c1-ac75-4495-933c-38427049241c.png)

**Comment by wangwenbo3307** [comment]
This problem has been resolved
