### ISSUE TITLE
Buttons - Click "Floating action buttons" in "Ready for more" at the bottom and error 500 is reported 

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#244]
![0 - 500](https://user-images.githubusercontent.com/95004531/149087978-ba3e1470-532c-4719-8918-b7314b803afb.png)
![500](https://user-images.githubusercontent.com/95004531/149088010-939b1d89-775a-4ef8-ac76-05bfcc5e84e7.png)

**Comment by capdiem** [comment]
Resovled.
