### ISSUE TITLE
Item groups , After reversing the example, gray or another color is recommended

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#273]
![After reversing the example, gray or another color is recommended](https://user-images.githubusercontent.com/95004531/149482263-3fe85f31-fc9f-45f9-8ea1-21c67047b650.png)

**Comment by capdiem** [comment]
示例里显式给Card设置了Dark，所以没办法自动翻转颜色。可能有办法做到反转，但会在示例代码里写许多跟示例无关的代码，会影响示例代码的可读性。@doddgu
