### ISSUE TITLE
The home page layout is incorrect

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#277]
https://user-images.githubusercontent.com/95004531/149737345-aa45b412-d8ed-4d82-a480-35320681a7a9.mp4

**Comment by LazyEar0** [comment]
The service site has this problem

https://user-images.githubusercontent.com/95004531/150662207-6cd7e564-15a5-4808-9349-5619da597936.mp4

**Comment by wangwenbo3307** [comment]
This problem has been resolved
