### ISSUE TITLE
There are several incomplete translations in the document

### ISSUE THREAD

**Issue by dotnet9** [BlazorComponent/MASA.Blazor#288]
Watching the Chinese Spring Festival Gala, I didn't forget to check your documents. I found several incomplete translations.
![微信图片_20220131210331](https://user-images.githubusercontent.com/19390373/151798809-6bc25cfb-c022-4d6f-a625-3b89a3c2c0cf.png)

**Comment by dotnet9** [comment]
![ItemGroups](https://user-images.githubusercontent.com/19390373/151799036-898cf102-71ec-4ead-86f6-36a7d2bdd523.png)

**Comment by dotnet9** [comment]
![Buttons](https://user-images.githubusercontent.com/19390373/151799491-1d40ccbf-a665-4015-b119-51e9559f948a.png)

**Comment by doddgu** [comment]
Got it, thanks.
