### ISSUE TITLE
The picture cannot be displayed using the MImage component under the MTabsItems component

### ISSUE THREAD

**Issue by 15168440402** [BlazorComponent/MASA.Blazor#301]
![image](https://user-images.githubusercontent.com/30889371/153985177-1fc9b2fa-ca43-420d-8d5e-1bc4b369642b.png)
![image](https://user-images.githubusercontent.com/30889371/153985303-f341c14e-bd0d-4a9c-aa76-5634b7ac43a3.png)

 <MAvatar Size="120">
    <MImage Contain Src="https://cdn.masastack.com/stack/images/website/masa-blazor/logo.png" />
</MAvatar>

**Comment by 15168440402** [comment]
<MAvatar Size="120">
                        <MImage Contain Src="https://cdn.masastack.com/stack/images/website/masa-blazor/logo.png" />
                    </MAvatar>

**Comment by capdiem** [comment]
It seems to have been solved, can't repro now.
