### ISSUE TITLE
The MSnackbar component uses the TimeOut property to report an error

### ISSUE THREAD

**Issue by 15168440402** [BlazorComponent/MASA.Blazor#302]
Unable to set property 'TimeOut' on object of type 'MASA.Blazor.MSnackbar'. The error was: Unable to cast object of type 'System.String' to type 'System.Int32'.

**Comment by wangzengxing** [comment]
This is not an error for snackbar but for any component which use snackbar

**Comment by capdiem** [comment]
I contacted @15168440402 on my own initiative and found that he had used the wrong way. So close this.
