### ISSUE TITLE
ErrorHandler - Click the button and the page will flash

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#369]
https://user-images.githubusercontent.com/95004531/160988984-f6bcb4ba-4a97-4423-b1aa-dc10b941e8c3.mp4

**Comment by Qinyouzeng** [comment]
This test case is click the button,the button background  color change to red

**Comment by doddgu** [comment]
So, your example can be described in more detail in case people don't understand
