### ISSUE TITLE
[by accident]Editor，Image cannot be uploaded

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#381]
![image](https://user-images.githubusercontent.com/95004531/161215043-adc21d50-227a-4c85-86c9-ce31c566e581.png)

https://user-images.githubusercontent.com/95004531/161216425-f8afb1cc-8b70-4904-acf9-2ec720e03a43.mp4

**Comment by wzh425** [comment]
Uploading the same file continuously does not trigger onchange.  I have solved it. #382
