### ISSUE TITLE
【UI组件】【了解更多】中的内容标题没有（）翻译成中文。

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#40]
如题
![image-2021-12-02-13-23-16-145](https://user-images.githubusercontent.com/95004531/146324603-2eb40d09-b932-43fb-81a2-089f6e762e4a.png)
![image-2021-12-02-13-21-56-283](https://user-images.githubusercontent.com/95004531/146324608-50e1352a-5f63-4de4-a553-de69593beb08.png)

**Comment by capdiem** [comment]
#862 fixed this.
