### ISSUE TITLE
【UI组件】Time pickers - 对话框和菜单，时间选择器再次点击不显示

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#44]
UI组件 - Time pickers - 示例 - 对话框和菜单；
示例中第一个时间选择器选中时间后，点击第二个时间选择器，修改时间后，关闭第二个时间选择器，再次点击第二个时间选择器，弹出浮层但不显示时间选择器，浮层无法关闭，详见附件视频；

https://user-images.githubusercontent.com/95004531/146324013-304242a1-3852-49d0-9d20-93da3013f566.mp4

**Comment by LazyEar0** [comment]
按视频步骤操作后，再次点击时间选择器，第一次不出现，第二次点击才出现时间选择器

**Comment by wangzengxing** [comment]
This is caused by dialog.
