### ISSUE TITLE
移动版文档侧栏下方会丢失一部分高度

### ISSUE THREAD

**Issue by DonPangPang** [BlazorComponent/MASA.Blazor#448]
**环境：**
Android 12, 最新版Edge浏览器

**操作：**
进入官网，点击文档，展开侧边栏，向上滑动，侧边栏和正文都会出现样式问题，侧边栏底部高度不能填充整个页面，正文部分底部样式和正文样式出现错乱。

https://user-images.githubusercontent.com/49866401/167412382-4fa45f6d-d0d7-4abe-bd56-550b7b7a2cb1.mp4

**Comment by doddgu** [comment]
Fixed in 0.6
