### ISSUE TITLE
Treeview 可选择项  如何在数据加载后自动选中 ？

### ISSUE THREAD

**Issue by YataoFeng** [BlazorComponent/MASA.Blazor#449]
Treeview 可选择项  如何在数据加载后自动选中 ？
How can treeview selectable items be automatically selected after data loading?

需求：
Demand：
   用户上次已经选择过了项，用户下次请求的时候希望看到上次选择过的。
   The user has selected items last time. The user wants to see the items selected last time when he requests next time.

目前控件是否支持？请举个例子。
Is the current control supported? Please give an example.

**Comment by doddgu** [comment]
treeview文档里有个 可选择 的例子，你可以看一下
