### ISSUE TITLE
文本框输入过快时会丢失字符

### ISSUE THREAD

**Issue by LittleFish-233** [BlazorComponent/MASA.Blazor#461]
组件的文本框内会丢字符，用相同速度在github的文本框中输入则不会

![1652357275671_](https://user-images.githubusercontent.com/53342258/168071773-7b4dd4e5-aaa9-4787-b265-356a5ffa09ba.gif)

**Comment by doddgu** [comment]
我这边重现不出来，我让开发同学看一下

**Comment by doddgu** [comment]
此问题是同时按下多个按键，导致OnInput在Blazor Server下处理会有问题。已与楼主沟通，同时按键的需求不高，先关闭归档处理。
