### ISSUE TITLE
语言本地化Json支持嵌套

### ISSUE THREAD

**Issue by zyknow** [BlazorComponent/MASA.Blazor#462]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

#### 支持 user_layout.version 像这样使用
i18n.T("user_layout.version")
![_KA%{R(ENA2Z1VFT(X@ 1{4](https://user-images.githubusercontent.com/49929368/168209711-9f07b310-07ad-4c0c-a82d-a4feebca4063.png)

**Comment by doddgu** [comment]
Fixed, https://github.com/BlazorComponent/BlazorComponent/pull/131
