### ISSUE TITLE
Please add or change TitleText to English on Menu right click on PageTab

### ISSUE THREAD

**Issue by boc2010** [BlazorComponent/MASA.Blazor#504]
**Is your feature request related to a problem? Please describe.**
I'm using template Masa.Blazor.Pro
How to fix Menu Tabs to Multi language in Component, Please. Thank
[
![image](https://user-images.githubusercontent.com/49285229/173757728-aac1a54e-b396-4b6d-870a-d623dd26d1d1.png)
](url)
Link : https://github.com/BlazorComponent/BlazorComponent/blob/dc45d8a1b45f5851f0ea88b7ae6497f7a8336efb/src/Component/BlazorComponent/Components/PageTabs/Tab/Menu/BPageTabsMenu.razor

**Comment by doddgu** [comment]
If it's not urgent, we'll schedule a fix later.
