### ISSUE TITLE
Is there support web notifications

### ISSUE THREAD

**Issue by Rhaegarlai** [BlazorComponent/MASA.Blazor#514]
**Is your feature request related to a problem? Please describe.**
i can't find web notifications component,i wonder that it's supported yet?

**Comment by doddgu** [comment]
MASA Blazor is just the UI, community need implement by your self. If you want about `Message Inbox` component, we provide it in MASA.Stack.Component. It's based on the MASA Stack design style.

**Comment by Rhaegarlai** [comment]
> MASA Blazor is just the UI, community need implement by yourself. If you want about `Message Inbox` component, we provide it in MASA.Stack.Component. It's based on the MASA Stack design style.

But i find that there is a notification component in Blazor Bootstrap UI,like BrowserNotification,maybe it's because the design concept is different.
After all,thank you for your replay,I've already implemented the functionality in JS,by C# invoke.

**Comment by capdiem** [comment]
Yes, we don't have any similar features at present, you can implement it yourself.
