### ISSUE TITLE
关于使用富文本上传图片发现的一些问题

### ISSUE THREAD

**Issue by gitapteryx** [BlazorComponent/MASA.Blazor#531]
1，MEditorUpload 上传配置 的Token 和 TokenName 是放在body里进行pos提交 而非 head 里，最终我是吧token 放在url里解决的。
2，图片上传成功后，后端返回的 标准格式是什么？目前上传成功后还不知如何将图片回显到 富文本控件里

谢谢~

**Comment by doddgu** [comment]
@wzh425

**Comment by wzh425** [comment]
1、Token是应该在head上 我将修正它，在0.5中可以得到支持
2、上传后，默认会使用返回数据的path字段作为图片url ,您也可以通过Upload参数的PathKey指定图片字段

**Comment by wzh425** [comment]
您也可以自己处理上传逻辑 可以参考文档示例 https://blazor.masastack.com/components/editor
