### ISSUE TITLE
MSelect 提供方法关闭下拉

### ISSUE THREAD

**Issue by tky753** [BlazorComponent/MASA.Blazor#542]
**Is your feature request related to a problem? Please describe.**
使用`PrependItemContent`或`AppendItemContent`增加内容后点击增加的内容，无法自动触发关闭下拉框，
能否提供方法手动触发关闭？

**Describe the solution you'd like**
MSelect 加一个public 方法，关闭下拉框。

**Describe alternatives you've considered**

**Additional context**

**Comment by doddgu** [comment]
@capdiem

**Comment by capdiem** [comment]
try this:
``` cshtml
<MSelect @ref="Select" />

@code {
     private MSelect Select { get; set; }
     
     private void OnClick() {
         Select.Blur();
     }
}
```
