### ISSUE TITLE
背景颜色显示影响文本颜色, 颜色名称与传RGB效果不同

### ISSUE THREAD

**Issue by DonPangPang** [BlazorComponent/MASA.Blazor#545]
如图, 在页面中我已经给组件设置了Dark的属性, 传red, orange等颜色参数, 显示正常, 但是当我传入RGB时, 底色可以正常显示, 但是字体无法正常显示.
![image](https://user-images.githubusercontent.com/49866401/176628509-8fad502a-a3e7-452e-a298-c0deebcf704e.png)

![{F7NF@DPTTI3RLAKN$TFLW2](https://user-images.githubusercontent.com/49866401/176628231-bdb8de8d-bbdb-4bf8-a78e-43ca1a953144.png)

**Comment by capdiem** [comment]
there is a more beautiful [ColorChip](https://github.com/masastack/MASA.Stack.Components/blob/main/src/Masa.Stack.Components/PureComponents/ColorChip.cs) component that inherits **MChip**.

**Comment by DonPangPang** [comment]
> there is a more beautiful [ColorChip](https://github.com/masastack/MASA.Stack.Components/blob/main/src/Masa.Stack.Components/PureComponents/ColorChip.cs) component that inherits **MChip**.

okey. Thanks.
