### ISSUE TITLE
Quill 富文本 如何开启图片的缩放功能？

### ISSUE THREAD

**Issue by gitapteryx** [BlazorComponent/MASA.Blazor#548]
如题谢谢！~

**Comment by capdiem** [comment]
你是想在编辑模式下调整图片的大小吗？

**Comment by gitapteryx** [comment]
> 你是想在编辑模式下调整图片的大小吗？

是的

**Comment by capdiem** [comment]
不支持，但quilljs社区可以通过 [quill-blot-formatter](https://github.com/Fandom-OSS/quill-blot-formatter)  来实现调整。我们可以支持一下，但不会在0.5.0中发布。

**Comment by capdiem** [comment]
示例预览：[Editor-模块](https://masa-blazor-docs-dev.lonsid.cn/components/editor)
