### ISSUE TITLE
MTextField绑定byte类型数据输入浮点数报异常，如何优雅地抓取并提示错误

### ISSUE THREAD

**Issue by tky753** [BlazorComponent/MASA.Blazor#554]
`<MTextField Type="number">`绑定**byte**类型数据输入 浮点数，报异常
`System.ArgumentException: x.x is not a valid value for Byte. (Parameter 'value')`
想要像其他验证一样，通过**Rules**来处理，但根本走不到Rules
现在只能用`<MErrorHandler>`包裹，（包裹后也走不到**Rules**那里）

是不是我的做法有问题，应该绑定decimal类型，然后在后端再转成byte来处理？
或者有没有什么方法能控制输入字符?

**Comment by tky753** [comment]
想要实现效果，可以输入 浮点数，但是可以通过Rules验证显示错误，并且无法保存

**Comment by tky753** [comment]
> 想要实现效果，可以输入 浮点数，但是可以通过Rules验证显示错误，并且无法保存

想想还是**绑定decimal**或者**控制输入字符**更合理一点。
想问一下，有没有办法`控制输入字符`？

**Comment by capdiem** [comment]
控制输入字符的话你就不能使用`type=number`

**Comment by tky753** [comment]
> 控制输入字符的话你就不能使用`type=number`

是不是要在keydown事件里preventDefault，这在blazor里很难搞吧

**Comment by tky753** [comment]
> 控制输入字符的话你就不能使用`type=number`

或者你是说绑定string 属性，在set里直接修改值？

**Comment by capdiem** [comment]
本来我认为原生的`@oninput`和`@onchange`能解决你的问题，你可以通过`args.Value`拿到输入的字符串，但是`MTextField`存在了`OnInput`和`OnChange`参数，以至于你不能访问到原生的`@oninput`和`@onchange`。

**Comment by tky753** [comment]
暂时改成绑定到一个decimal变量里，这样Rules就走的到了，然后在保存前赋值到保存对象里，这应该是改动最小的解决方案了

**Comment by tky753** [comment]
就是保存前的验证，要手动验证这个decimal对象了
