### ISSUE TITLE
MTextarea根据内容动态调整高度

### ISSUE THREAD

**Issue by tky753** [BlazorComponent/MASA.Blazor#561]
**Is your feature request related to a problem? Please describe.**
需要在更改**MTextarea**内容后，动态调整height。
尝试计算出行数，再更新`Rows`，但没有效果，这个属性的值似乎只在初始化的时候加载一次？
那后续要怎么通过程序修改height？

**Describe the solution you'd like**
更新`Rows`后，同步渲染显示的行数

**Comment by doddgu** [comment]
AutoGrow 属性不是自动算的么？你是想自己控制？

**Comment by tky753** [comment]
> AutoGrow 属性不是自动算的么？你是想自己控制？

@doddgu  `AutoGrow`设置了，但是好像只有通过在界面上按回车才会自动增长，如果直接修改`@bind-Value`，是没有效果的

**Comment by doddgu** [comment]
@capdiem PTAL

**Comment by capdiem** [comment]
是一个BUG，存在直接修改Value没有自动增长。

**Comment by doddgu** [comment]
github的hook自动关闭了。下个版本发布后如果还有问题可以再reopen
