### ISSUE TITLE
某些组件不监听resize事件

### ISSUE THREAD

**Issue by DonPangPang** [BlazorComponent/MASA.Blazor#577]
例如Tab组件, 当缩小到一定程度, 小屏样式未加载, 需要点击后.

https://user-images.githubusercontent.com/49866401/178443659-132ebd92-187a-4fb0-ba0b-27994b4bf135.mp4

**Comment by capdiem** [comment]
@DonPangPang  BlazorComponent/BlazorComponent#309 fixed this
