### ISSUE TITLE
能不能适配下echart的饼图/散点图之类的？

### ISSUE THREAD

**Issue by jingshui127** [BlazorComponent/MASA.Blazor#581]
MASA现在的图标控件还比较少，如果能把echart常用图形集成到里面就好了。谢谢

**Comment by doddgu** [comment]
ECharts 我们只是帮忙做了 Options 的传参，只要官网例子里面的Options从js转成C#的对象即可。理论上来说绝大多数都可以正常使用，你可以先试一下，如果遇到实际问题导致无法使用可以跟我们反馈，谢谢。

**Comment by jingshui127** [comment]
> ECharts 我们只是帮忙做了 Options 的传参，只要官网例子里面的Options从js转成C#的对象即可。理论上来说绝大多数都可以正常使用，你可以先试一下，如果遇到实际问题导致无法使用可以跟我们反馈，谢谢。

非常感谢。
昨天已经把曲线都搞好了。
好用。
祝越来越好

**Comment by doddgu** [comment]
客气，谢谢支持，那issue就先关闭了。有问题再reopen
