### ISSUE TITLE
Mselect and MAutoComplete support  VirtualScroll

### ISSUE THREAD

**Issue by 15168440402** [BlazorComponent/MASA.Blazor#587]

**Comment by doddgu** [comment]
MSelect don't support search. Why it need support virtual scroll? Do you think it's ok for many items in MSelect?

**Comment by 15168440402** [comment]
MAutoComplete现在继承的Mselect，那MAutoComplete需要考虑下如何重构

**Comment by doddgu** [comment]
And if MAutoComplete use remote api for search, it don't need VirtualScroll yet.
I think only MAutoComplete use local content(or only init items once from server), the scene is OK.

**Comment by doddgu** [comment]
> MAutoComplete现在继承的Mselect，那MAutoComplete需要考虑下如何重构

You can support VirtualScroll for all, but I don't think it's a good choice.

**Comment by doddgu** [comment]
I don't think that's a good requirement. Close it first.
