### ISSUE TITLE
Can not select text when textbox in list.

### ISSUE THREAD

**Issue by jim-jiang-github** [BlazorComponent/MASA.Blazor#589]
Can not select text when textbox in list.

https://user-images.githubusercontent.com/29189410/181516370-4d5f4c06-0326-4ba0-ab92-25fe19e5c23b.mp4

**Comment by doddgu** [comment]
@capdiem PTAL

**Comment by capdiem** [comment]
@jim-jiang-github 
I cannot reproduce this problem in 0.4, please provide a reproducible demo.
Here's the code I'm trying to reproduce:
``` html
<MCard>
    <MList>
            <MListItem>
                <MListItemContent>
                    <MTextField @bind-Value="value" Label="Label"></MTextField>
                </MListItemContent>
            </MListItem>
    </MList>
</MCard>
```

**Comment by jim-jiang-github** [comment]
![image](https://user-images.githubusercontent.com/29189410/182018711-5c16cc04-3adf-41b3-9463-06a547123e1d.png)

You should put the List into a dialog, I use the official demo (https://github.com/BlazorComponent/MASA.Blazor.git), and then put the sample code in the body of ‘MainLayout.razor’ to reproduce this bug.

**Comment by capdiem** [comment]
I still can't reproduce it in v0.4 and v0.5. I first press ctrl a to select all (or select through the mouse), and then press ctrl c to copy.

**Comment by jim-jiang-github** [comment]
[MasaWebApp1.zip](https://github.com/BlazorComponent/MASA.Blazor/files/9232365/MasaWebApp1.zip)

Here is the mini sample.
