### ISSUE TITLE
需求：希望支持设置 ECharts 初始化参数

### ISSUE THREAD

**Issue by LittleFish-233** [BlazorComponent/MASA.Blazor#594]
目前无法设置 ECharts 初始化参数，例如：切换深色模式，切换渲染模式

**预期效果**
ECharts 组件添加 Dark 属性指示是否为深色模式，或者使用其它办法设置深色模式

![image](https://user-images.githubusercontent.com/53342258/182121523-356080d2-85e3-4045-8aea-2431fc41bc41.png)

**Comment by doddgu** [comment]
已经修复，等 0.6.0-preview.3 发版

**Comment by capdiem** [comment]
0.6.0-preview.3 已发。
