### ISSUE TITLE
MASA Blazor Pro 文档描述与模板项目不一致

### ISSUE THREAD

**Issue by ktwoq** [BlazorComponent/MASA.Blazor#608]
**Describe the bug**
MASA Blazor 文档描述与模板项目不一致，如图：文档描述：Blazor Server引入资源文件，在 Pages/_Host.cshtml 中引入资源文件。
MasaWebApp项目模板引入资源文件在Pages/_Layout.cshtml中
![image](https://user-images.githubusercontent.com/79044546/183909806-b828ca56-6f35-470b-bfb5-2dbb17779707.png)

**Comment by capdiem** [comment]
文档有误，应放在 **_Layout.cshtml**。

**Comment by doddgu** [comment]
文档只有正式版才会发布，需要等到0.6正式上线才可以。预计8月底，谢谢反馈。
