### ISSUE TITLE
Select and AutoComplete support drop down list customization

### ISSUE THREAD

**Issue by jim-jiang-github** [BlazorComponent/MASA.Blazor#612]
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/29189410/184499150-4e80548a-624d-439c-8269-8d4a62b1327e.png)

I hope the drop down list can support customization. And I can set any components here.

**Comment by capdiem** [comment]
Is it enough to use the `ItemContent` slot?
```razor
<MAutocomplete>
  <ItemContent Context="data">
    <MListItemAvatar Color="indigo" Class="text-h5 font-weight-light white--text">
        @data.Item.Name[0]
    </MListItemAvatar>
    <MListItemContent>
        <MListItemTitle>
            @data.Item.Name
        </MListItemTitle>
        <MListItemSubtitle>
            @data.Item.Symbol
        </MListItemSubtitle>
    </MListItemContent>
    <MListItemAction>
        <MIcon>mdi-bitcoin</MIcon>
    </MListItemAction>
  </ItemContent>
</MAutocomplete>
```

**Comment by jim-jiang-github** [comment]
> 

Not enough, the result I want is to customize the content structure of the entire drop down box. For example, I want the drop down box to be displayed in a Grid or to support virtualization, not just item.

**Comment by jim-jiang-github** [comment]
> Is it enough to use the `ItemContent` slot?
> 
> ```
> <MAutocomplete>
>   <ItemContent Context="data">
>     <MListItemAvatar Color="indigo" Class="text-h5 font-weight-light white--text">
>         @data.Item.Name[0]
>     </MListItemAvatar>
>     <MListItemContent>
>         <MListItemTitle>
>             @data.Item.Name
>         </MListItemTitle>
>         <MListItemSubtitle>
>             @data.Item.Symbol
>         </MListItemSubtitle>
>     </MListItemContent>
>     <MListItemAction>
>         <MIcon>mdi-bitcoin</MIcon>
>     </MListItemAction>
>   </ItemContent>
> </MAutocomplete>
> ```

Not enough, the result I want is to customize the content structure of the entire drop down box. For example, I want the drop down box to be displayed in a Grid or to support virtualization, not just item.

**Comment by capdiem** [comment]
No, we won't support it. There is a lot of work to be done if we are going to support this feature. Without default or custom `ItemContent`, the component will lose a lot of features, such as keyboard events. And you currently can't control whether the pop-up layer is displayed or not. 
You can use **MMenu** an and **MTextField** to do what you want.
