### ISSUE TITLE
EChart组件本地化示例未正确显示

### ISSUE THREAD

**Issue by LittleFish-233** [BlazorComponent/MASA.Blazor#613]
文档站点 https://masa-blazor-docs-dev.lonsid.cn/components/echarts 本地化示例异常

![image](https://user-images.githubusercontent.com/53342258/184506217-0be37ca5-4aa0-401f-8e10-6f92c1e6bb24.png)

**Comment by capdiem** [comment]
是的，发布之后会出现，正在排查
