### ISSUE TITLE
BDelayable 组件在 maui-blazor、Android API 28(9.0)环境下执行报错

### ISSUE THREAD

**Issue by Qinyouzeng** [BlazorComponent/MASA.Blazor#624]
### 环境 ###

- MAUI blazor
- Android API 28
- MASA Blazor 0.5.0

### 问题复现步骤 ###
使用MDialog弹窗组件，真机调试时，打开包含弹窗组件的页面时，必然报错，错误信息：

`Unexpected token =
SyntaxError: Unexpected token =`

堆栈信息：
`
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16``1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at BlazorComponent.BDelayable.OnAfterRenderAsync(Boolean firstRender) in D:\workplaces\MASA.Blazor\src\BlazorComponent\src\Component\BlazorComponent\Mixins\Delayable\BDelayable.cs:line 31`

### 初步调试结果 ###
可能是Android API 28版本webview 还不支持 `class` ，延迟加载js中使用了 

`class Delayable {  ...`

我经过调试，把 `class` 替换成js 的 `function` 代码后，该错误消失了
修改前 
``` javascript
class Delayable {
    _dotNetHelper = {};
    _openDelay = 0;
    _closeDelay = 0;
    _openTimeout;
    _closeTimeout;
    
    constructor(dotNet, openDelay, closeDelay) {
        this._dotNetHelper = dotNet;
        this._openDelay = openDelay;
        this._closeDelay = closeDelay;
    }

    clearDelay() {
        clearTimeout(this._openTimeout);
        clearTimeout(this._closeTimeout);
    }

    runDelay(type, cb) {
        this.clearDelay();

        if (type === "open") {
            const delay = parseInt(this._openDelay, 10);

            this._openTimeout = setTimeout(cb || (() => {
                this._dotNetHelper.invokeMethodAsync('SetActive', true);
            }), delay)
        } else {
            const delay = parseInt(this._closeDelay, 10);

            this._closeTimeout = setTimeout(cb || (() => {
                this._dotNetHelper.invokeMethodAsync('SetActive', false);
            }), delay)
        }
    }
}
```

修改后：

``` javascript
function delayable(dotNet, openDelay, closeDelay) {
   let _dotNetHelper = dotNet ,
    _openDelay = openDelay||0,
    _closeDelay = closeDelay||0,
    _openTimeout,
    _closeTimeout;

    function clearDelay() {
        clearTimeout(_openTimeout);
        clearTimeout(_closeTimeout);
    }

    function runDelay(type, cb) {
        clearDelay();

        if (type === "open") {
            const delay = parseInt(_openDelay, 10);

            _openTimeout = setTimeout(cb || (() => {
                _dotNetHelper.invokeMethodAsync('SetActive', true);
            }), delay)
        } else {
            const delay = parseInt(_closeDelay, 10);

            _closeTimeout = setTimeout(cb || (() => {
                _dotNetHelper.invokeMethodAsync('SetActive', false);
            }), delay)
        }
    }

    return this;
}
```

**Comment by capdiem** [comment]
cannot reproduce in v1

**Comment by GlodenBoy** [comment]
同样出现了~
![image](https://github.com/masastack/MASA.Blazor/assets/2329528/3cbf417e-84a4-4078-9191-14e11d68c898)

**Comment by Qinyouzeng** [comment]
使用的masa blazor版本，手机的版本等，和其他信息尽量详细写提供些，在新版本该问题已经修复，如果使用的是低版本的masa blazor，还是需要自己解决的。

**Comment by GlodenBoy** [comment]
> 使用的masa blazor版本，手机的版本等，和其他信息尽量详细写提供些，在新版本该问题已经修复，如果使用的是低版本的masa blazor，还是需要自己解决的。

是使用的nuget最新版的，这个我是在安卓手机里钉钉打开masa项目报的错，钉钉应该使用的是安卓的webview 内核，这个在PC上是没有出现的。

**Comment by capdiem** [comment]
@GlodenBoy 用的 0.6.2 ？还是1.0.0-rc3？

**Comment by GlodenBoy** [comment]
> @GlodenBoy 用的 0.6.2 ？还是1.0.0-rc3？

额，我看了一下 获取的 nuget版本是0.6.2，不知道为啥不是1.0.x，应该是预览版的原因， 没注意....  因为这个原因，我最后胡彦成用小程序写了...
