### ISSUE TITLE
Current dotnet workloads do NOT cover maui-android

### ISSUE THREAD

**Issue by JeremyWu917** [BlazorComponent/MASA.Blazor#634]
**Describe the bug**
> error NETSDK1147: To build this project, the following workloads must be installed: maui-android

We just need upgrade CI [here](https://github.com/BlazorComponent/MASA.Blazor/blob/982feb630ffed5fff3a2393017e6e722e11a3dfa/.github/workflows/azure-static-web-apps-agreeable-plant-0c2439c10.yml#L28) and [here](https://github.com/BlazorComponent/MASA.Blazor/blob/982feb630ffed5fff3a2393017e6e722e11a3dfa/.github/workflows/pr.yml#L21)

![image](https://user-images.githubusercontent.com/54832272/189356251-b5e75f8d-3230-4dde-bb17-8d5452884dcd.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/54832272/189357536-e1ab3fb9-4bc2-4974-834f-01e9d2734b67.png)

**Comment by doddgu** [comment]
Yes, I just wait the pr merged. And split CI by folder.

**Comment by doddgu** [comment]
@mixvii 麻烦根据目录把CI拆成两部分。具体的节后沟通。
