### ISSUE TITLE
ECharts组件在Chrome78版本无法正常使用

### ISSUE THREAD

**Issue by LittleFish-233** [BlazorComponent/MASA.Blazor#635]
使用Chrome78版本时，ECharts组件无法工作

可能是Chrome版本过低不支持什么特性吧，话说有确定最低支持到Chrome哪个版本吗？

当前版本：0.6-preview6
最后正常的版本：0.5

OS: Linux
OSArchitecture: X64
ProcessArchitecture: X64
Framework: .NET 6.0.3
Message: Unexpected token '.'
SyntaxError: Unexpected token '.'
*********************************************
StackTrace: at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
at Masa.Blazor.MECharts.OnAfterRenderAsync(Boolean firstRender)
at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

![image](https://user-images.githubusercontent.com/53342258/189509516-1bc06f8e-20c0-4222-b81a-d747db337c12.png)

**Comment by doddgu** [comment]
@capdiem 新的api应该要提供最低浏览器支持列表

**Comment by capdiem** [comment]
fixed by #681.
