### ISSUE TITLE
文档网站Wasm版导航栏选中后不会取消选中

### ISSUE THREAD

**Issue by DonPangPang** [BlazorComponent/MASA.Blazor#657]
文档网站导航栏第一个不会取消选中，或者说一直有一个灰色背景，稳定浮复现。
![RM}HPW{8@}(S@PC @DL1B{Q](https://user-images.githubusercontent.com/49866401/191517495-3c0422ac-e47b-443d-a610-b1f947dd6e07.png)

**Comment by doddgu** [comment]
@capdiem PTAL

**Comment by capdiem** [comment]
0.5 wasm下ripple效果有问题，[0.6](http://masa-blazor-docs-wasm-dev.lonsid.cn/getting-started/installation)已修复。

**Comment by doddgu** [comment]
issue先关了，如果有问题再重新打开

**Comment by DonPangPang** [comment]
> issue先关了，如果有问题再重新打开

okk
