### ISSUE TITLE
能否把每次新添加的内容标注出来?

### ISSUE THREAD

**Issue by DonPangPang** [BlazorComponent/MASA.Blazor#661]
这次看6.x的文档发现左侧导航栏标记了一些组件是预置还是JS代理，但是有一个问题，很难发现哪些组件或者能力是新增的，在以后的版本里能否添加一个[新增]的Tag标记一下。

**Comment by capdiem** [comment]
我们会在文档重构之后加入该功能。

**Comment by capdiem** [comment]
`1.0.0-preview.4` 将在导航栏使用带颜色的点标记新增还是更新，[发行说明](https://docs.masastack.com/blazor/getting-started/release-notes)也会上线。
