### ISSUE TITLE
【UI组件】Groups-Item groups了解更多-Carousels轮播跳转后页面404 

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#67]
如题
![image-2021-12-02-11-22-10-506](https://user-images.githubusercontent.com/95004531/146344288-b02cb293-7508-482b-b04f-37864ac6432c.png)
![image-2021-12-02-11-22-05-296](https://user-images.githubusercontent.com/95004531/146344299-c0889304-975d-4c97-b42b-5a708dd5bda4.png)

**Comment by wangzengxing** [comment]
We have disabled it.

**Comment by capdiem** [comment]
resolved.
