### ISSUE TITLE
分辨率变化后menu弹出位置错误

### ISSUE THREAD

**Issue by diyer03th** [BlazorComponent/MASA.Blazor#673]
**Describe the bug**
menu弹出的位置错误。

**To Reproduce**
1、第一次通过点击button弹出菜单，菜单弹出的位置是正确的。
2、当页面的分辨率发生变化后，原来的button位置已经发生变化，但menu弹出的位置没有改变。造成menu的位置错误。

**Expected behavior**
希望分辨率变化后，menu的位置能跟随button一起变化到正确的位置。

**Screenshots**

1
![1664274696475](https://user-images.githubusercontent.com/8527803/192503071-bc94b189-8146-43e1-8cd9-1389b433066a.png)

2
![1664274732326](https://user-images.githubusercontent.com/8527803/192503190-90673f20-e5aa-492a-ba69-fe19a1fef235.png)

3
![1664274781365](https://user-images.githubusercontent.com/8527803/192503353-62310869-ed5b-4a49-997e-aec230d8bb25.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser ：Chromium
 - Version ：103

**Comment by doddgu** [comment]
@capdiem PTAL

**Comment by capdiem** [comment]
@diyer03th 你的情况是列表的数量变了，列表的高度变高了，自动把button挤下来了，我看了vueitfy的行为也是如此，所以不打算处理。我建议你点击完之后关闭menu（启用`CloseOnContentClick`），下次点开时会重新计算高度。

**Comment by doddgu** [comment]
如果有疑义可以reopen，暂时先关闭了
