### ISSUE TITLE
Repo Separation?

### ISSUE THREAD

**Issue by JeremyWu917** [BlazorComponent/MASA.Blazor#674]
Hi there,

Is there any plan to separate this repo, cause current cost storge more then 100M.

Thanks

![16642731408100](https://user-images.githubusercontent.com/54832272/192509625-2a773230-a383-40c0-b7fb-146df2d7ba52.png)

**Comment by doddgu** [comment]
We will try to solve it in 1.0

**Comment by capdiem** [comment]
@JeremyWu917 thanks for contacting us. We decided to use monorepo, so we're not going to split it.
