### ISSUE TITLE
The left menu will pop up automatically

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#697]
Server ： 移动端
左侧菜单会自动弹出

https://user-images.githubusercontent.com/95004531/195042294-f54f3854-39d0-4bf9-97eb-dd590854a37c.mp4

**Comment by capdiem** [comment]
0.6.0-rc.7解决了这个问题，不过开发环境的文档还没更新

**Comment by LazyEar0** [comment]
resolved
