### ISSUE TITLE
【UI组件】Text fields报错404

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#7]
【UI组件】Text fields报错404
@wangzengxing 
修复版本：0.3.0
![报错404](https://user-images.githubusercontent.com/95004531/146303393-1a62962b-a0fa-4128-b932-2d7f3bdd9a92.png)

**Comment by wangzengxing** [comment]
Duplicate of #6  
Thanks for contact us,we will fixed as soon as possible!
