### ISSUE TITLE
ListItem . The page is stuck and cannot slide

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#701]
Server : 移动端
上滑浏览组件后，下滑查看已浏览过的内容，页面卡顿，无法滑动

https://user-images.githubusercontent.com/95004531/195064125-78516baa-e6cf-4674-b0ad-64a938302976.mp4

**Comment by capdiem** [comment]
#711 fixed this.

**Comment by LazyEar0** [comment]
resolved
