### ISSUE TITLE
MobilePickerView . By default, Selected has no value

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#702]
Server & wasm ：Web ， 移动端
示例：级联，默认情况下，Selected没有值。
![image](https://user-images.githubusercontent.com/95004531/195235357-6b1fe529-4a92-47ed-849f-f9232b745e62.png)

**Comment by capdiem** [comment]
正常行为，因为左侧没有选择。

**Comment by doddgu** [comment]
但是默认看着像是选中了北京-海淀区。并且如果不滑动再回来，海淀区也选不上。要么默认加一个请选择，要么默认选中海淀区。

**Comment by LazyEar0** [comment]
resolved
