### ISSUE TITLE
MobileDateTimePicker . The year of the popover is not fully displayed

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#703]
Server & wasm ：移动端
示例：格式化，弹窗的年份显示不全
![36b4ef07-cd03-4d09-b1b4-7031d6e66fd7](https://user-images.githubusercontent.com/95004531/195237951-9de285f4-701b-4f19-bead-8e4b1fd973d2.jpg)

**Comment by capdiem** [comment]
应该不算是一个BUG吧 😢

**Comment by doddgu** [comment]
算，示例应该要让显示完整
