### ISSUE TITLE
MobileTimePicker . The pop-up time is different from the default time

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#704]
Server & wasm ： Web，移动端
示例：最大值和最小值，打开弹窗后的时间与默认时间不一致
![image](https://user-images.githubusercontent.com/95004531/195236631-85466b14-4430-4f9a-8605-a6f45a707a39.png)

**Comment by capdiem** [comment]
最小值设置的是9.30，但在弹窗赋值之前是默认值0点，所以是正常行为。

**Comment by capdiem** [comment]
#709 把时间格式的本地化移除了，不再出现`上午`、`下午`。

**Comment by doddgu** [comment]
如果最小值是9：30。而0点不在范围内，则外面也不应该会是0。

**Comment by capdiem** [comment]
> 如果最小值是9：30。而0点不在范围内，则外面也不应该会是0。

有没有默认值是用户自己定义的，没定义默认值当然展示的是00:00:00。

**Comment by doddgu** [comment]
如果允许的值是 1-100，那没有人会定义到这个值之外，除非它定义为0，并实际显示的值是请选择。这样给它一个特殊的含义业务上才说得通。

**Comment by doddgu** [comment]
https://blazor.masastack.com/components/sliders#Sliders
比如 silder组件，它就是个范围值组件，它的默认值就不可能超出这个范围。一定要超出这个范围就要有一个看似合理的业务来覆盖这个让人迷惑的问题。

**Comment by capdiem** [comment]
新增的时候没多少人会去在乎实例化有没有给TimeOnly类型的值因为业务上有最大值最小值而去赋一个范围内的值 😃

**Comment by doddgu** [comment]
按照讨论的结果，这个issue暂时关闭，重新起一个 增强功能的issue，后面支持在touch过程中有一个悬浮的tooltip显示完整值。
