### ISSUE TITLE
建议：发布的时候把文档也带上，不知道怎么使用的时候习惯性F12进去看说明。

### ISSUE THREAD

**Issue by wosperry** [BlazorComponent/MASA.Blazor#714]
建议：发布的时候把文档也带上，比如有些类型是字符串的，但是不看文档不知道有哪些字符串是可以用的

![image](https://user-images.githubusercontent.com/55421194/196025922-86b50b34-71a2-4d2a-a93a-1696bb9ac19e.png)

![image](https://user-images.githubusercontent.com/55421194/196025963-9e6efb6c-90e9-45e5-a549-42804581bc73.png)
![image](https://user-images.githubusercontent.com/55421194/196025978-8f23181f-26aa-4c22-b13c-3f5d6488a2b7.png)

**Comment by doddgu** [comment]
这个应该支持枚举
