### ISSUE TITLE
Can not load razor page from a razor library in Samples/Maui project

### ISSUE THREAD

**Issue by charleypeng** [BlazorComponent/MASA.Blazor#719]
after create a new razor class library and referenced it into Masa.Maui.Windows project,  when I add this page into "nav.json" and run the app, click this item it returns an error page: "Sorry, there's nothing at this address", but when I copy this ".razor" file into Masa.Maui.Windows, it works fine.

**Comment by doddgu** [comment]
If it doesn't solve your problem, you can reopen this issue.
