### ISSUE TITLE
引入组件 @attributes="@context.Attrs" 报错: “AuthenticationState”未包含“Attrs”的定义

### ISSUE THREAD

**Issue by Caspersure** [BlazorComponent/MASA.Blazor#751]
在[头像与菜单结合的用法](https://blazor.masastack.com/components/avatars)中,我将组件复制进我的程序中 ,报了这样的错误:
 ` error CS1061: “AuthenticationState”未包含“Attrs”的定义，并且找不到可接受
第一个“AuthenticationState”类型参数的可访问扩展方法“Attrs”(是否缺少 using 指令或程序集引用?)`
然后我把这个`@attributes="@context.Attrs"`去掉之后报错消失了,但是我的组件没办法像官网那样展开菜单
![image](https://user-images.githubusercontent.com/62390646/197972681-ac066c37-81c6-4efc-a1d9-433d1dda5473.png)
在此之前我已经按照官网的usage步骤将组件库进行了引入,希望作者大大解答一下,谢谢啦~

**Comment by doddgu** [comment]
ActivatorContext的Context重新定义一个新的名字，比如下面例子的 activatorContext，然后用这个activatorContext 试试。
```razor
<ActivatorContent Context="activatorContext">
    <MButton @attributes="@activatorContext.Attrs">
    </MButton>
</ActivatorContent>
```
