### ISSUE TITLE
如何在 WPF Blazor 中使用 MASA

### ISSUE THREAD

**Issue by melinyi** [BlazorComponent/MASA.Blazor#762]
MASA官方文档视乎没有提供入门教程。

下面是WPF 创建Blazor项目微软的官方教程。
https://learn.microsoft.com/zh-cn/aspnet/core/blazor/hybrid/tutorials/wpf?view=aspnetcore-6.0

**Comment by doddgu** [comment]
的确，早期我们只提供了 Blazor Server 和 Blazor Wasm 的入门教程。新的文档站点正在制作中，我们希望新的文档站点内容可以更完善，如果你对wpf blazor比较熟悉，也欢迎你能给我们提供wpf blazor的入门教程或demo。甚至包括MAUI Blazor也都可以。

**Comment by melinyi** [comment]
我是看到这篇文章知道MASA的
https://dotnet9.com/2022/10/wpf-with-blazor-chat-test

但是它是前后端分离，我不清楚MASA具体在何处被引入。

**Comment by doddgu** [comment]
Blazor Hybrid 和 BlazorWebView 你可以查一下

**Comment by melinyi** [comment]
/// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            var serviceCollection = new ServiceCollection();
            serviceCollection.AddWpfBlazorWebView();
            **serviceCollection.AddMasaBlazor();**
            Resources.Add("services", serviceCollection.BuildServiceProvider());
       
        }
    }
