### ISSUE TITLE
0.6.x 官方文档左侧侧边导航栏BUG

### ISSUE THREAD

**Issue by DonPangPang** [BlazorComponent/MASA.Blazor#765]
某种特殊的情况下，左侧导航栏向上滚动，无法滚动到顶部。
上方的【介绍】【快速入门】等无法看到。Wasm和Server模式都存在。
复现过程：展开左侧导航栏，向下滚动，将浏览器宽度收缩直到导航栏自动收纳，再次将浏览器缩放到最大，向上滚动左侧导航栏，即可复现无法到顶部的现象，稳定复现。
![image](https://user-images.githubusercontent.com/49866401/199979353-e7300954-8f73-4ca2-8f4f-2316df97ba20.png)

**Comment by doddgu** [comment]
@capdiem PTAL

**Comment by capdiem** [comment]
旧文档已经不维护了，此问题经过测试也没有复现，所以先关闭了。
