### ISSUE TITLE
pagination（分页）组件，按钮的数量超过了父容器，但未从中间截断

### ISSUE THREAD

**Issue by LittleFish-233** [BlazorComponent/MASA.Blazor#768]
按钮的数量超过了父容器，但是没有从中间截断，官网示例如下

![image](https://user-images.githubusercontent.com/53342258/200844795-1ee6148f-106e-4c5e-8a6f-44b9e66a986a.png)

最后正常的版本：0.5

**Comment by doddgu** [comment]
感谢反馈
