### ISSUE TITLE
MTabs第一次打开时默认激活项和切换后样式不一致。

### ISSUE THREAD

**Issue by china-live** [BlazorComponent/MASA.Blazor#775]
有个类似的需求 #683
 
![QQ图片20221114153052](https://user-images.githubusercontent.com/12002799/201600736-22509e92-2cff-4fdf-82dc-c29cdd275527.png)
![第一次打开时的样式](https://user-images.githubusercontent.com/12002799/201601137-1ebbb20c-0287-47e7-95e7-61f1e5327364.png)
 
![切换后的样式](https://user-images.githubusercontent.com/12002799/201601139-8110ebc4-ce6a-4934-8fc7-e13a89b7a52d.png)

**Comment by capdiem** [comment]
跟 #683 不是一个问题哈~

**Comment by china-live** [comment]
这个bug刚好满足了#683的需求

**Comment by capdiem** [comment]
Thanks for contacting us, it would be fixed in `1.0.0-preview.3`.
