### ISSUE TITLE
【UI组件】Skeleton Loaders - 示例，查看源代码缺少“code” 

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#78]
以下示例，查看源代码缺少“code” 
1.使用；
![骨架装载器 - 样板组件 查看源代码缺少“code”](https://user-images.githubusercontent.com/95004531/146346038-642e51c1-8d03-4f38-b4a5-c1e6c9becfe0.png)
![骨架装载器 - 使用 查看源代码缺少“code”](https://user-images.githubusercontent.com/95004531/146346047-a0d3a220-751d-4484-917a-bd0f5ac22d7b.png)
2.样板组件

**Comment by wangzengxing** [comment]
Please ignore this.
