### ISSUE TITLE
【UI组件】Data tables - 点击API “MEditDialog”报错404

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#8]
Data tables - 点击API “MEditDialog”报错404
修复版本：0.3.0
![报错404](https://user-images.githubusercontent.com/95004531/146316755-7f8dba02-1004-4220-b45d-6883d415e899.png)

**Comment by wangzengxing** [comment]
No MEditDialog now.

**Comment by wangzengxing** [comment]
No MEditDialog component yet.
