### ISSUE TITLE
Progress circular（进度环）背景环颜色自定义

### ISSUE THREAD

**Issue by melinyi** [BlazorComponent/MASA.Blazor#801]
无法对 Progress circular 进行背景色自定义，需添加相关属性进行设置。

**Comment by capdiem** [comment]
通过Style设置background-color不行吗？

**Comment by melinyi** [comment]
![image](https://user-images.githubusercontent.com/83648656/202836109-d4d1fece-3ab9-4eae-a6db-71ade868d516.png)
 style="background-color:blue"
 
尝试无效

**Comment by capdiem** [comment]
你意思是给环的背景加颜色吗？默认是灰色的那段？

**Comment by melinyi** [comment]
> 你意思是给环的背景加颜色吗？默认是灰色的那段？

是的，或者可以设置跟随主环颜色的50%透明度进行设置。

类似 https://www.themoviedb.org/ 这样评分的进度环。
