### ISSUE TITLE
BUG 页脚组件 遮挡内容？

### ISSUE THREAD

**Issue by melinyi** [BlazorComponent/MASA.Blazor#805]
![image](https://user-images.githubusercontent.com/83648656/202905041-f2236e89-733f-403c-8bc5-462ff587fc88.png)

偶尔出现这个情况，页脚挡住了内容，内部空间高度未正确计算。

**Comment by doddgu** [comment]
@capdiem

**Comment by capdiem** [comment]
偶尔出现Main的padding-bottom没计算正确？有能稳定复现的情况吗？

**Comment by melinyi** [comment]
> 偶尔出现Main的padding-bottom没计算正确？有能稳定复现的情况吗？

我怀疑是 `@foreach` 渲染合集时，未全部渲染造成的。有时刷新一下就可以了。

**Comment by capdiem** [comment]
`<MFooter App></MFooter>`  App开启后 `MMain` 的padding-bottom应该是固定的，应该不会因为`MMain`内容的变化而影响。

**Comment by melinyi** [comment]
可以把滚动条固定到main中吗，这样可以解决这个问题吧？

**Comment by capdiem** [comment]
有可以复现的repo吗？

**Comment by capdiem** [comment]
Duplicate of #813
