### ISSUE TITLE
BUG 导航MNavigationDrawer遮挡页脚

### ISSUE THREAD

**Issue by melinyi** [BlazorComponent/MASA.Blazor#813]
![image](https://user-images.githubusercontent.com/83648656/203324440-d0168b27-c87a-452d-8c8f-145ce4429653.png)

设置了如下属性。切换页面后恢复正常。首次加载会出现BUG。

` <MAppBar App ClippedLeft ElevateOnScroll>`

`<MNavigationDrawer App Clipped>`

`<MFooter App>`

**Comment by capdiem** [comment]
#847 may have fixed this issue.

**Comment by capdiem** [comment]
经测试，已不存在此问题。
