### ISSUE TITLE
拖动组件在server模式下的克隆有问题

### ISSUE THREAD

**Issue by aidenwlf** [BlazorComponent/MASA.Blazor#830]
https://user-images.githubusercontent.com/101579695/205601439-156d0429-0753-48f8-ae98-5b00df8fd02b.mp4

这里就会像这个后面会有一下往上排

**Comment by capdiem** [comment]
没太懂，Server和Wasm下行为是一样的吧？

**Comment by aidenwlf** [comment]
不知道，但是就是不一样，你们可以去试一下

**Comment by capdiem** [comment]
@Qinyouzeng

**Comment by Qinyouzeng** [comment]
@aidenwlf  没有看明白你说的意思，你是克隆后ui渲染的时候有个明显的ui加载效果吗？

我们这边组件复制时，组件跟blazor进行了状态的同步，因为前端复制出来一个新的组件，blazor此时是不知道的，需要进行与balzor进行状态同步，然后ui渲染，所以会有一个明显的渲染。

如果是这个问题，并且你有更好的解决方案也欢迎给我们提pr，或者你可以更加详细的描述下你的问题 。
