### ISSUE TITLE
BUG：GithubIssues.razor中MemoryCache变量依赖导致整个项目界面无法被加载

### ISSUE THREAD

**Issue by xiyuan0727** [BlazorComponent/MASA.Blazor#831]
现象如下：
![image](https://user-images.githubusercontent.com/58834860/205656579-53535874-75ae-4f61-849f-5ce9285e15e4.png)

错误信息：
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot provide a value for property 'MemoryCache' on type 'Masa.Docs.Shared.Components.GitHubIssues'. There is no registered service of type 'Microsoft.Extensions.Caching.Memory.IMemoryCache'.
System.InvalidOperationException: Cannot provide a value for property 'MemoryCache' on type 'Masa.Docs.Shared.Components.GitHubIssues'. There is no registered service of type 'Microsoft.Extensions.Caching.Memory.IMemoryCache'.

操作拉取：主分支中的eb9239e69ca8a571bd36ced83d937fe88bd655a6提交：feat(right-nav): add right nav style and get github issues data (#822)
BlazorComponent已拉取到最新代码：04e41261a4bc5ca63b6c007732e8f3a686924a6a：fix(Treeview): missing style (#259)
后启动WebAssembly项目就会出现整个页面无法呈现，检查错误信息发现出现：blazor.webassembly.js:1 
        
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot provide a value for property 'MemoryCache' on type 'Masa.Docs.Shared.Components.GitHubIssues'. There is no registered service of type 'Microsoft.Extensions.Caching.Memory.IMemoryCache'.
System.InvalidOperationException: Cannot provide a value for property 'MemoryCache' on type 'Masa.Docs.Shared.Components.GitHubIssues'. There is no registered service of type 'Microsoft.Extensions.Caching.Memory.IMemoryCache'.这个错误信息，
无论是Masa.Blazor.NewDocs.sln还是Masa.Blazor.sln项目生成都会出现这个错误，尝试过拉取main分支最新代码该问题仍是会出现

尝试注释GithubIssues.razor中
   // [Inject]
   // public IMemoryCache MemoryCache { get; set; } = null!;

        protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            _httpClient = HttpClientFactory.CreateClient("github");

            //_openCount = await MemoryCache.GetOrCreateAsync<string?>(OPEN_ISSUES_KEY, entry =>
            //{
            //    entry.AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(1);
            //    return GetIssuesCountAsync(OPEN_ISSUES_URL);
            //});

            //_closeCount = await MemoryCache.GetOrCreateAsync<string?>(CLOSED_ISSUES_KEY, entry =>
            //{
            //    entry.AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(1);
            //    return GetIssuesCountAsync(CLOSED_ISSUES_URL);
            //});

            //StateHasChanged();
        }
    }

发现页面可以正常加载，所以怀疑MemoryCache的接口导致

**Comment by doddgu** [comment]
@codding-y

**Comment by codding-y** [comment]
resolved, pull the latest code
