### ISSUE TITLE
PopupService的Alert的Rounded应该怎么使用

### ISSUE THREAD

**Issue by Yu-Core** [BlazorComponent/MASA.Blazor#860]
![2022-12-27_025704](https://user-images.githubusercontent.com/96511239/209576876-e454474e-789a-45ee-94b6-afbacf92538a.png)

![image](https://user-images.githubusercontent.com/96511239/209577666-f323adf6-74d5-4615-a873-bedd1ecd962f.png)

![image](https://user-images.githubusercontent.com/96511239/209576970-1cb8509a-283a-4c94-8b4d-a671978dbde8.png)

param.Rounded = true;Alert的形状没有任何变化。Rounded是否应该是string类型而不是bool类型？

**Comment by capdiem** [comment]
是的，应该为 `StringBoolean` 类型。
