### ISSUE TITLE
PopupService的Confirm的按钮的位置不正确

### ISSUE THREAD

**Issue by Yu-Core** [BlazorComponent/MASA.Blazor#874]
PopupService的Confirm的按钮的位置不正确，在部分手机浏览器（如夸克浏览器、X浏览器）和MAUI Blazor 安卓 (测了安卓12的虚拟机和安卓11的真机)
应该与`justify-content: end;`有关。不支持`justify-content: end;`，只支持`justify-content: flex-end;`

![Screenshot_2022-12-29-05-58-27-703](https://user-images.githubusercontent.com/96511239/209876603-758ce947-fab2-46d0-8058-728b7db1bc64.png)

![image](https://user-images.githubusercontent.com/96511239/209875450-fc958abe-94d7-4297-af63-cc40bedb3fa1.png)

![image](https://user-images.githubusercontent.com/96511239/209875533-c16affcf-896a-485c-9bb3-c25fe0dfdba5.png)

**Comment by capdiem** [comment]
兼容问题，能提个PR解决该问题吗？

**Comment by Yu-Core** [comment]
@capdiem 已提交，第一次提PR，不知道操作的对不对

**Comment by capdiem** [comment]
@Yu-Core 已经合并，多谢PR！
