### ISSUE TITLE
希望能支持.net 7.0

### ISSUE THREAD

**Issue by mookeview** [BlazorComponent/MASA.Blazor#892]
当前版本在.net 7.0 Blazor下编译不通过，希望能尽快支持新版本！

MasaBlazor非常棒，感谢你们的工作！

**Comment by doddgu** [comment]
新版文档站点就是 .net 7，直接用的现有组件库，没有发现问题。能提供详细错误信息？

**Comment by mookeview** [comment]
我重新试了下，原来是我这边的问题，现在一切OK，谢谢！

**Comment by doddgu** [comment]
那先关闭了
