### ISSUE TITLE
希望表格支持长字符串省略显示

### ISSUE THREAD

**Issue by HongChenLuYuan** [BlazorComponent/MASA.Blazor#905]
如题，希望表格支持长字符串省略显示。

**Comment by doddgu** [comment]
表格默认不会支持自动文本截断。但你可以通过控制列的class来达到相同的效果。文档在：https://blazor.masastack.com/stylesandanimations/text-and-typography

**Comment by HongChenLuYuan** [comment]
明白了，感谢指导。

**Comment by HongChenLuYuan** [comment]
没用，表格列使用截断css class根本不生效




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BlazorComponent/MASA.Blazor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月11日(星期三) 上午9:27
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [BlazorComponent/MASA.Blazor] 希望表格支持长字符串省略显示 (Issue #905)





 
如果满意可以给个star支持一下，谢谢

**Comment by HongChenLuYuan** [comment]
好的用div生效了，我昨天用的span标签，当时是没生效，还有这样做了后表格组件指定width属性的就算是废了。
谢谢指导。




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "BlazorComponent/MASA.Blazor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月11日(星期三) 上午10:55
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [BlazorComponent/MASA.Blazor] 希望表格支持长字符串省略显示 (Issue #905)





 
我写了个伪代码，你看一下。目前 context.Header 还没有把属性都传给DataTable，有点小问题。通过加一个 div 的 文本阶段和限制宽度就可以解决。
         <ItemColContent&gt;             @if (context.Header.Value == nameof(WeatherForecast.Date))             {                 @context.Item.Date.ToShortDateString()             }             else if (context.Header.Value == nameof(WeatherForecast.Summary))             {                 <div class="text-truncate" style="width: ***@***.***</div&gt;             }             else             {                 @context.Value             }         </ItemColContent&gt;

**Comment by doddgu** [comment]
DataTable 上次重构改出了点小问题，1.0会抽时间修复一下。到时候可以不需要自己再套Div了，通过Header设置CellClass + Width即可。
我先关闭issue了，有问题可以随时reopen。
