### ISSUE TITLE
MMenu组件激活后再次点击激活它的元素，无法关闭

### ISSUE THREAD

**Issue by Yu-Core** [BlazorComponent/MASA.Blazor#907]
MMenu组件激活后再次点击激活它的元素，无法关闭。在Vuetify中是可以的。

https://user-images.githubusercontent.com/96511239/211390298-f1e03a81-0e0b-41bc-9375-bac74cdbc9b2.mp4

https://user-images.githubusercontent.com/96511239/211390455-667dc00f-2a47-40d1-931d-84dd132d90fe.mp4

**Comment by doddgu** [comment]
感谢反馈
