### ISSUE TITLE
文档站点Carousels中文描述错误

### ISSUE THREAD

**Issue by Ramon403** [BlazorComponent/MASA.Blazor#908]
文档站点中文描述错误
![图片](https://user-images.githubusercontent.com/2922635/211495309-b511df36-97a3-45e9-a1a8-d3b064a0e820.png)

Carousels 这个节点对应的是 轮播 吧

文档地址：https://docs.masastack.com/blazor/components/carousels

**Comment by doddgu** [comment]
感谢反馈
