### ISSUE TITLE
MAppBar中使用MMenu，位置不正确

### ISSUE THREAD

**Issue by Yu-Core** [BlazorComponent/MASA.Blazor#917]
![image](https://user-images.githubusercontent.com/96511239/211929944-ea8b470d-15a3-4bf8-a524-2715eea87bb9.png)
![image](https://user-images.githubusercontent.com/96511239/211930002-089f809f-a3c0-4849-a5d0-fb4c909157a5.png)

![image](https://user-images.githubusercontent.com/96511239/211929475-ec928ab0-66db-48ea-b642-13c9f83c2e34.png)
![image](https://user-images.githubusercontent.com/96511239/211929551-087ab0d6-f242-4a21-89b8-dbe88ad08a10.png)

**Comment by capdiem** [comment]
Thanks for contacting us, it would be fixed in `1.0.0-preview.3`.

**Comment by Yu-Core** [comment]
@capdiem Other components also have this problem
![2023-03-10_054953](https://user-images.githubusercontent.com/96511239/224171675-abcc4530-7599-4094-965b-7bf23f440ae0.png)
![2023-03-10_055056](https://user-images.githubusercontent.com/96511239/224171751-5e5dd7db-1d71-4009-9642-5d0d738ea31f.png)
![2023-03-10_060448](https://user-images.githubusercontent.com/96511239/224171799-eac97a9a-4929-4fc5-8b41-00567dfda4a7.png)
I think css should be modified, `first-child` and `last-child`  are changed to `first-of-type` and `last-of-type`
```
.m-application--is-ltr .m-toolbar__content > .m-btn.m-btn--icon:first-of-type, .m-application--is-ltr .m-toolbar__extension > .m-btn.m-btn--icon:first-of-type {
    margin-left: -12px
}

.m-application--is-rtl .m-toolbar__content > .m-btn.m-btn--icon:first-of-type, .m-application--is-rtl .m-toolbar__extension > .m-btn.m-btn--icon:first-of-type {
    margin-right: -12px
}

.m-application--is-ltr .m-toolbar__content > .m-btn.m-btn--icon:last-of-type, .m-application--is-ltr .m-toolbar__extension > .m-btn.m-btn--icon:last-of-type {
    margin-right: -12px
}

.m-application--is-rtl .m-toolbar__content > .m-btn.m-btn--icon:last-of-type, .m-application--is-rtl .m-toolbar__extension > .m-btn.m-btn--icon:last-of-type {
    margin-left: -12px
}
```
I'm not sure if this will cause other problems

**Comment by capdiem** [comment]
@Yu-Core CSS我们不打算改，因为是直接搬的vuetify的。你说的问题和Menu一样，https://github.com/BlazorComponent/BlazorComponent/pull/307 只是把 Activator 和 Content 的位置互换了一下，Dialog估计也是这样的问题，如果可以请提个PR帮忙解决一下。

**Comment by Yu-Core** [comment]
@capdiem 
![image](https://user-images.githubusercontent.com/96511239/224234634-8084d385-f365-4106-a74d-f091696b3695.png)

额，Activator 和 Content 的位置互换只能解决放在右边的问题，放在左边位置又不对了，MMenu现在就是这样。

**Comment by capdiem** [comment]
@Yu-Core 你说的对，我只能假定 Material Design 设计语言不会在Appbar的第一个button上做Menu相关的设计。你若觉得还是不妥，你仍然可以提修改CSS的PR，但是是修改 masa-blazor.extend.css 。
