### ISSUE TITLE
【UI组件】Button groups - 工具栏，示例部分功能缺失 

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#93]
如题
![按钮组 - 工具栏示例功能不全](https://user-images.githubusercontent.com/95004531/146348133-03c12e59-21d4-40d9-a219-4f12bd8de529.png)

**Comment by capdiem** [comment]
Overflow button组件没有开发，Vueitfy3目前也没有迁移该组件，所以这个示例先删除处理了。
