### ISSUE TITLE
调试上传文件时，vs调试时，如果浏览器有打开的页面，上传文件并报错；调试时，如果浏览器没有打开的页面，则正常。

### ISSUE THREAD

**Issue by yifaruanjian** [BlazorComponent/MASA.Blazor#941]
调试上传文件时，vs调试时，如果浏览器有打开的页面，上传文件并报错；调试时，如果浏览器没有打开的页面，则正常。
![image](https://user-images.githubusercontent.com/33993150/212828989-4243c29c-810c-4e18-be09-08b3c03cd9af.png)

**Comment by doddgu** [comment]
麻烦提供一个可以复现的简易的demo，节后开发同学可以快速排查一下

**Comment by yifaruanjian** [comment]
开发环境：VS2022

**Comment by doddgu** [comment]
@capdiem PTAL

**Comment by capdiem** [comment]
空文本文件也会这样吗？

**Comment by bingbingtalk** [comment]
是选择文件后项目异常终止了吗？如果是的话需要修改一下VS配置，取消选中“工具>选项>项目和解决方案>web项目>在浏览器窗口关闭时停止调试程序，在调试停止时关闭浏览器”试试。

**Comment by bingbingtalk** [comment]
https://www.cnblogs.com/lanrenka/p/16460199.html

**Comment by doddgu** [comment]
没有反馈暂时先关闭，有需要可以reopen
