### ISSUE TITLE
How to locate router with Bottom Navigation?

### ISSUE THREAD

**Issue by LuohuaRain** [BlazorComponent/MASA.Blazor#947]
```c#
<NavLink href="example-page" target="_blank">Example page</NavLink>
```

```c#
<MBottomNavigation></MBottomNavigation>
```

_MBottomNavigation_ doesn't have property like native Blazor component _NavLink_ 'href', so do I have to control blazor navigation router manually?

**Comment by doddgu** [comment]
For example:
```razor
<MBottomNavigation
    @bind-Value="value"
    Color="primary">
    <MButton>
        <span>Recents</span>

        <MIcon>mdi-history</MIcon>
    </MButton>

    <MButton>
        <span>Favorites</span>

        <MIcon>mdi-heart</MIcon>
    </MButton>

    <MButton>
        <span>Nearby</span>

        <MIcon>mdi-map-marker</MIcon>
    </MButton>
</MBottomNavigation>
```

The you should control navigation router with button. And the button has `Href` property.

**Comment by capdiem** [comment]
Currently, only List supports automatic route matching (`Linkage` is enabled), while Tabs and BottomNavigation do not support it. Should I put it in 1.0.0? @doddgu

**Comment by doddgu** [comment]
I think it can be supported in 2.0.

**Comment by blackmaple** [comment]
我也需要这功能 能加急下么

**Comment by doddgu** [comment]
@capdiem 调整这个需要多久，1.0能来得及么？

**Comment by capdiem** [comment]
来得及，比较简单

**Comment by capdiem** [comment]
Thanks for contacting us, it would be supported in `1.0.0-preview.2`.
