### ISSUE TITLE
Carousels组件点击分隔符无法切换到对应轮播图

### ISSUE THREAD

**Issue by LittleFish-233** [BlazorComponent/MASA.Blazor#948]
如以下视频中所示，设置 `Cycle=true` 后，点击下方的分隔符没有反应，手动切换正常

https://user-images.githubusercontent.com/53342258/213615309-222c5314-d6b4-4c0c-93e0-b5969b3b1f05.mp4

当前版本：1.0-preview
最后正常的版本：0.6

**Comment by doddgu** [comment]
过个好年，节后见 ^_^

**Comment by LittleFish-233** [comment]
预祝新年快乐o((>ω< ))o

**Comment by capdiem** [comment]
Thanks for contacting us, it would be fixed in `1.0.0-preview.3`.
