### ISSUE TITLE
【UI组件】Grid - 文案说明中无跳转链接 

### ISSUE THREAD

**Issue by LazyEar0** [BlazorComponent/MASA.Blazor#95]
UI组件 - Grid ；文案说明中无跳转链接，请自查调整
![网格- 文案描述中无跳转链接 (1)](https://user-images.githubusercontent.com/95004531/146348415-a1c904c9-5758-4f22-9efa-24ab511cd11d.png)

**Comment by wangzengxing** [comment]
There is no breakpoint page now.
