### ISSUE TITLE
MTreeview组件的ActiveClass属性功能异常

### ISSUE THREAD

**Issue by mookeview** [BlazorComponent/MASA.Blazor#954]
<img width="1034" alt="bug" src="https://user-images.githubusercontent.com/121916399/214071362-b44ec7a4-554d-4f9b-a027-fa401d9cfe34.png">
.node_active{
    color: #673AB7 ;
    background:#EDE7F6;
    }
我想改变Node激活时的背景和字体颜色，通过ActiveClass赋值操作，但好像有Bug，具体如图所示。

**Comment by capdiem** [comment]
Thanks for contacting us, it would be fixed in `1.0.0-preview.2`.
