### ISSUE TITLE
Hope Alert components generated by PopupService can be rendered sequentially like Toast, rather than being covered with each other.

### ISSUE THREAD

**Issue by CuteLeon** [BlazorComponent/MASA.Blazor#958]
**Is your feature request related to a problem? Please describe.**
PopupService generated alerts are covered by each other, earlier popped Alerts are hidden.

**Describe the solution you'd like**
Hope Alert components generated by PopupService can be rendered sequentially like Toast, rather than being covered with each other.

**Comment by capdiem** [comment]
Why not apply Toast, because the style is different from Material Design? @CuteLeon

**Comment by CuteLeon** [comment]
Got it, it shouldn't display in that way according to the guideline here: https://m3.material.io/components/snackbar/guidelines , that's cool.

**Comment by capdiem** [comment]
@CuteLeon 1.0.0-preview has removed the toasts and make snackbar stacked using EnqueueSnackbar.

**Comment by CuteLeon** [comment]
That's great, and I saw that in offical documentation portal.
