### ISSUE TITLE
EChart wrapped in MTabItem would have width=100 when initialized for the first time 

### ISSUE THREAD

**Issue by LinQiaoPorco** [BlazorComponent/MASA.Blazor#968]
**Describe the bug**
EChart wrapped in MTabItem would have width=100 when initialized for the first time.
The width would become normal when eny actions trigger the update, such as Select the slicer or change the screen width.

**To Reproduce**
1. Create 'MTabItem' elemen;
2. Put a 'MECharts' element into 'MTabItem', with parameter as 'MinWidth = 500";
3. Run the blazor page, the EChart was not in correct width when first time loaded;

**Expected behavior**
EChart should have correct width even in MTabItem;

**Screenshots**
![image](https://user-images.githubusercontent.com/76023599/216277826-009180b1-4b16-4261-a674-d4033addfc90.png)

**Desktop (please complete the following information):**
 - Browser chrome

**Comment by capdiem** [comment]
Thanks for contacting us, it would be fixed in `1.0.0-preview.2`.
