### ISSUE TITLE
Some elements can not be accessed when anonymous

### ISSUE THREAD

**Issue by LinQiaoPorco** [BlazorComponent/MASA.Blazor#984]
**Describe the bug**
Some elements can not be accessed when anonymous.

**To Reproduce**
1. Set-up a blazor server template with MASA
2. Add login/out function to the blazor
3. Take a page as [AllowAnonymous]
4. Put a MCard and MTabItems to the page
5. See the MCard and MTabItems invisible when not log in

**Expected behavior**
Elements shall be visible when the razor page was marked as [AllowAnonymous]

**Screenshots**
![Issue 1](https://user-images.githubusercontent.com/76023599/217165283-3cbc5a93-f65d-42aa-ba43-799933d61e43.png)
![Issue 2](https://user-images.githubusercontent.com/76023599/217165373-f6ab33c0-b17c-44ce-adc3-9ecebdc965bd.png)

![image](https://user-images.githubusercontent.com/76023599/217165627-748d6845-4c87-4cdf-8bb0-9360d10f3d2b.png)

 - Browser [chrome]

**Comment by capdiem** [comment]
@LinQiaoPorco can not be reproduced, if you can, please provide a source code or repository that can be reproduced.
