### ISSUE TITLE
官方文档的预置布局代码能否重新补充下?

### ISSUE THREAD

**Issue by daoywy** [BlazorComponent/MASA.Blazor#986]
查看预置布局发现每个点开都是404, 能不能重新上传下? 不然想摆个Inbox都不会. 只能用别的方式摆

**Comment by capdiem** [comment]
@daoywy 你可以直接访问[源码](https://github.com/BlazorComponent/MASA.Blazor/blob/main/src/Docs/Masa.Blazor.Docs/Examples/getting-started/wireframes/Base.razor)

**Comment by daoywy** [comment]
> @daoywy 你可以直接访问[源码](https://github.com/BlazorComponent/MASA.Blazor/blob/main/src/Docs/Masa.Blazor.Docs/Examples/getting-started/wireframes/Base.razor)

是的, 源码访问不了.
https://github.com/BlazorComponent/MASA.Blazor/tree/feature/application/src/Docs/Masa.Docs.Shared/examples/wireframes/discord
https://github.com/BlazorComponent/MASA.Blazor/tree/feature/application/src/Docs/Masa.Docs.Shared/examples/wireframes/inbox
通过右下角的跳转github都是404
