### ISSUE TITLE
MAUI Blazor模式下使用输入校验会出现无法点击的情况

### ISSUE THREAD

**Issue by daoywy** [BlazorComponent/MASA.Blazor#987]
**Describe the bug**

**To Reproduce**
1. 使用PModal弹出一个弹出一个输入框, 
2. 输入一串不满足条件的字符串
3. 错误提示变更模态框大小后尝试点击其他区域, 整个应用就只显示输入光标了, 无法点击.

**Desktop (please complete the following information):**
 - OS: windows 11
 - Version 0.6.0 & 1.0.0 preview-2

**Comment by capdiem** [comment]
@daoywy 能提供一下可复现的仓库或相关代码吗？

**Comment by daoywy** [comment]
> @daoywy 能提供一下可复现的仓库或相关代码吗？

抱歉, 我新开了一个项目复制代码过去又没问题了. 如果我能复现了再打开这个问题吧
