### ISSUE TITLE
Bottom navigation 的 InputValue属性 为false时，页面底部依然有内边距

### ISSUE THREAD

**Issue by Yu-Core** [BlazorComponent/MASA.Blazor#996]
![2023-02-09_234353](https://user-images.githubusercontent.com/96511239/217864277-0941bacb-6879-43ba-a0f6-cf3274d5bf6f.png)

<img src="https://user-images.githubusercontent.com/96511239/217864296-00aa006b-bc34-48a2-9cf5-8fd7dd7300ad.png" width="400"/>

**Comment by capdiem** [comment]
Thanks for contacting us, it would be fixed in `1.0.0-preview.3`.
